[2024-02-15 19:03:55,138] 96 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://10.207.82.33:8000
[2024-02-15 19:03:55,138] 96 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-02-15 19:04:01,927] 64 root - INFO - Dataframe Gathered
[2024-02-15 19:04:01,927] 1414 app - ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Saurabh\mlops ineuron\End to End Project\env\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Saurabh\mlops ineuron\End to End Project\env\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Saurabh\mlops ineuron\End to End Project\env\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Saurabh\mlops ineuron\End to End Project\env\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 31, in predict_datapoint
    preds = predict_pipeline(final_data)
TypeError: 'PredictPipeline' object is not callable
[2024-02-15 19:04:01,933] 96 werkzeug - INFO - 127.0.0.1 - - [15/Feb/2024 19:04:01] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
